kind: Deployment
apiVersion: apps/v1
metadata:
  name: default-backend
  annotations:
    "kots.io/exclude": '{{repl ConfigOptionEquals "nginx_ingress_controller" "0" }}'
  labels:
    kots.io/placeholder: repl{{ printf "'true'" }}repl{{ ConfigOption "labels" | nindent 4 }}  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: default-backend
  template:
    metadata:
      labels:
        app: default-backend
        kots.io/placeholder: repl{{ printf "'true'" }}repl{{ ConfigOption "labels" | nindent 8 }} 
    spec:
      serviceAccountName: harness-serviceaccount
      terminationGracePeriodSeconds: 60
      imagePullSecrets:
      - name: regcred
      containers:
      - name: default-http-backend
        image: k8s.gcr.io/defaultbackend-amd64:1.5
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi
        securityContext:
          runAsUser: 65534    
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: default-backend
  annotations:
    "kots.io/exclude": '{{repl ConfigOptionEquals "nginx_ingress_controller" "0" }}'
  labels:
    kots.io/placeholder: repl{{ printf "'true'" }}repl{{ ConfigOption "labels" | nindent 4 }}   
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: default-backend
  type: ClusterIP